--------------------------------------------------------
--  File created - Tuesday-November-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CICLU_STUDII
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."CICLU_STUDII" 
   (	"ID" NUMBER(1,0), 
	"NUME" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CURS
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."CURS" 
   (	"ID" NUMBER(3,0), 
	"DENUMIRE" VARCHAR2(50 BYTE), 
	"ID_PROFESOR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENT
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."DEPARTAMENT" 
   (	"ID" NUMBER(3,0), 
	"NUME_DEPARTAMENT" VARCHAR2(50 BYTE), 
	"ID_FACULTATE" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACULTATE
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."FACULTATE" 
   (	"ID" NUMBER(6,0), 
	"NUME" VARCHAR2(50 BYTE), 
	"STRADA" VARCHAR2(50 BYTE), 
	"NR" NUMBER(3,0), 
	"TELEFON" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRAD_PROFESOR
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."GRAD_PROFESOR" 
   (	"ID" NUMBER(1,0), 
	"GRAD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFERTA_EDUCATIONALA
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" 
   (	"ID" NUMBER(8,0), 
	"NUME" VARCHAR2(100 BYTE), 
	"ID_FACULTATE" NUMBER(6,0), 
	"ID_CICLU_STUDII" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFESOR
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."PROFESOR" 
   (	"ID" NUMBER(3,0), 
	"NUME" VARCHAR2(30 BYTE), 
	"PRENUME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ID_GRAD" NUMBER(1,0), 
	"ID_DEPARTAMENT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTIE
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."PROMOTIE" 
   (	"ID" NUMBER(8,0), 
	"ID_OFERTA_EDUCATIONALA" NUMBER(8,0), 
	"AN_INCEPUT" NUMBER(4,0), 
	"AN_SFARSIT" NUMBER(4,0), 
	"NR_LOCURI_BUGET" NUMBER(3,0), 
	"NR_LOCURI_TAXA" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTIE_STUDENT
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" 
   (	"ID_PROMOTIE" NUMBER(8,0), 
	"ID_STUDENT" NUMBER(8,0), 
	"ID_REPARTITIE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPARTITIE
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."REPARTITIE" 
   (	"ID" NUMBER(1,0), 
	"REPARTITIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "UNIVERSITATETEST"."STUDENT" 
   (	"ID" NUMBER(8,0), 
	"NUME" VARCHAR2(20 BYTE), 
	"PRENUME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence PK_CURS
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_CURS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_DEPARTAMENT
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_DEPARTAMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_FACULTATE
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_FACULTATE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_OFERTA_EDUCATIONALA
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_OFERTA_EDUCATIONALA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_PROFESOR
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_PROFESOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_PROMOTIE
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_PROMOTIE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PK_STUDENT
--------------------------------------------------------

   CREATE SEQUENCE  "UNIVERSITATETEST"."PK_STUDENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Index CICLU_STUDII_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."CICLU_STUDII_PK" ON "UNIVERSITATETEST"."CICLU_STUDII" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CURS_FK_ID_PROFESOR
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."CURS_FK_ID_PROFESOR" ON "UNIVERSITATETEST"."CURS" ("ID_PROFESOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."CURS_PK" ON "UNIVERSITATETEST"."CURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENT_FK_ID_FACULTATE
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."DEPARTAMENT_FK_ID_FACULTATE" ON "UNIVERSITATETEST"."DEPARTAMENT" ("NUME_DEPARTAMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."DEPARTAMENT_PK" ON "UNIVERSITATETEST"."DEPARTAMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACULTATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."FACULTATE_PK" ON "UNIVERSITATETEST"."FACULTATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GRAD_PROFESOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."GRAD_PROFESOR_PK" ON "UNIVERSITATETEST"."GRAD_PROFESOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFERTA_EDUCATIONALA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."OFERTA_EDUCATIONALA_PK" ON "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFERTA_EDUC_FK_CICLU_STUDII
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."OFERTA_EDUC_FK_CICLU_STUDII" ON "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ("ID_CICLU_STUDII") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFERTA_EDUC_FK_ID_FACULTATE
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."OFERTA_EDUC_FK_ID_FACULTATE" ON "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ("ID_FACULTATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_FK_ID_DEPARTAMENT
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROFESOR_FK_ID_DEPARTAMENT" ON "UNIVERSITATETEST"."PROFESOR" ("ID_DEPARTAMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_FK_ID_GRAD
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROFESOR_FK_ID_GRAD" ON "UNIVERSITATETEST"."PROFESOR" ("ID_GRAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_NUME
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROFESOR_NUME" ON "UNIVERSITATETEST"."PROFESOR" ("NUME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."PROFESOR_PK" ON "UNIVERSITATETEST"."PROFESOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFESOR_PRENUME
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROFESOR_PRENUME" ON "UNIVERSITATETEST"."PROFESOR" ("PRENUME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTIE_AN_SFARSIT
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROMOTIE_AN_SFARSIT" ON "UNIVERSITATETEST"."PROMOTIE" ("AN_SFARSIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTIE_FK_OFERTA_EDUC
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."PROMOTIE_FK_OFERTA_EDUC" ON "UNIVERSITATETEST"."PROMOTIE" ("ID_OFERTA_EDUCATIONALA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROMOTIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."PROMOTIE_PK" ON "UNIVERSITATETEST"."PROMOTIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPARTITIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."REPARTITIE_PK" ON "UNIVERSITATETEST"."REPARTITIE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERIE_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."SERIE_STUDENT_PK" ON "UNIVERSITATETEST"."PROMOTIE_STUDENT" ("ID_PROMOTIE", "ID_STUDENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SERIE_STUDENT_REPARTITIE
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."SERIE_STUDENT_REPARTITIE" ON "UNIVERSITATETEST"."PROMOTIE_STUDENT" ("ID_REPARTITIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_NUME
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."STUDENT_NUME" ON "UNIVERSITATETEST"."STUDENT" ("NUME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERSITATETEST"."STUDENT_PK" ON "UNIVERSITATETEST"."STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PRENUME
--------------------------------------------------------

  CREATE INDEX "UNIVERSITATETEST"."STUDENT_PRENUME" ON "UNIVERSITATETEST"."STUDENT" ("PRENUME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CICLU_STUDII
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."CICLU_STUDII" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."CICLU_STUDII" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."CICLU_STUDII" ADD CONSTRAINT "CICLU_STUDII_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURS
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."CURS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."CURS" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."CURS" MODIFY ("ID_PROFESOR" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."CURS" ADD CONSTRAINT "CURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENT
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."DEPARTAMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."DEPARTAMENT" MODIFY ("NUME_DEPARTAMENT" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."DEPARTAMENT" MODIFY ("ID_FACULTATE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."DEPARTAMENT" ADD CONSTRAINT "DEPARTAMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACULTATE
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."FACULTATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."FACULTATE" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."FACULTATE" ADD CONSTRAINT "FACULTATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRAD_PROFESOR
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."GRAD_PROFESOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."GRAD_PROFESOR" MODIFY ("GRAD" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."GRAD_PROFESOR" ADD CONSTRAINT "GRAD_PROFESOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFERTA_EDUCATIONALA
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ADD CONSTRAINT "OFERTA_EDUCATIONALA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" MODIFY ("ID_CICLU_STUDII" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" MODIFY ("ID_FACULTATE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" MODIFY ("ID_GRAD" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" MODIFY ("ID_DEPARTAMENT" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" ADD CONSTRAINT "PROFESOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOTIE
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("ID_OFERTA_EDUCATIONALA" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("AN_INCEPUT" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("AN_SFARSIT" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("NR_LOCURI_BUGET" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" MODIFY ("NR_LOCURI_TAXA" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" ADD CONSTRAINT "PROMOTIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOTIE_STUDENT
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" MODIFY ("ID_PROMOTIE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" MODIFY ("ID_STUDENT" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" MODIFY ("ID_REPARTITIE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" ADD CONSTRAINT "SERIE_STUDENT_PK" PRIMARY KEY ("ID_PROMOTIE", "ID_STUDENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPARTITIE
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."REPARTITIE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."REPARTITIE" MODIFY ("REPARTITIE" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."REPARTITIE" ADD CONSTRAINT "REPARTITIE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."STUDENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."STUDENT" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."STUDENT" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "UNIVERSITATETEST"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURS
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."CURS" ADD CONSTRAINT "CURS_FK1" FOREIGN KEY ("ID_PROFESOR")
	  REFERENCES "UNIVERSITATETEST"."PROFESOR" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENT
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."DEPARTAMENT" ADD CONSTRAINT "DEPARTAMENT_FK1" FOREIGN KEY ("ID_FACULTATE")
	  REFERENCES "UNIVERSITATETEST"."FACULTATE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFERTA_EDUCATIONALA
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ADD CONSTRAINT "OFERTA_EDUCATIONALA_FK1" FOREIGN KEY ("ID_FACULTATE")
	  REFERENCES "UNIVERSITATETEST"."FACULTATE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ADD CONSTRAINT "OFERTA_EDUCATIONALA_FK2" FOREIGN KEY ("ID_CICLU_STUDII")
	  REFERENCES "UNIVERSITATETEST"."CICLU_STUDII" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" ADD CONSTRAINT "PROFESOR_FK1" FOREIGN KEY ("ID_GRAD")
	  REFERENCES "UNIVERSITATETEST"."GRAD_PROFESOR" ("ID") ENABLE;
  ALTER TABLE "UNIVERSITATETEST"."PROFESOR" ADD CONSTRAINT "PROFESOR_FK2" FOREIGN KEY ("ID_DEPARTAMENT")
	  REFERENCES "UNIVERSITATETEST"."DEPARTAMENT" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTIE
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE" ADD CONSTRAINT "PROMOTIE_FK_OFERTA_EDUC" FOREIGN KEY ("ID_OFERTA_EDUCATIONALA")
	  REFERENCES "UNIVERSITATETEST"."OFERTA_EDUCATIONALA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROMOTIE_STUDENT
--------------------------------------------------------

  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" ADD CONSTRAINT "SERIE_STUDENT_FK_ID_PROMOTIE" FOREIGN KEY ("ID_PROMOTIE")
	  REFERENCES "UNIVERSITATETEST"."PROMOTIE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" ADD CONSTRAINT "SERIE_STUDENT_FK_ID_REPARTITIE" FOREIGN KEY ("ID_REPARTITIE")
	  REFERENCES "UNIVERSITATETEST"."REPARTITIE" ("ID") ENABLE;
  ALTER TABLE "UNIVERSITATETEST"."PROMOTIE_STUDENT" ADD CONSTRAINT "SERIE_STUDENT_FK_ID_STUDENT" FOREIGN KEY ("ID_STUDENT")
	  REFERENCES "UNIVERSITATETEST"."STUDENT" ("ID") ON DELETE CASCADE ENABLE;
